# yaml-language-server: $schema=https://json.schemastore.org/traefik-v3.json
## Base Traefik configuration
api:
  dashboard: true
  debug: true
  insecure: false

log:
  level: 'INFO'
accessLog:
  filePath: '/logs/access.log'

metrics:
  addInternals: true
  prometheus:
    addEntryPointsLabels: true
    addRoutersLabels: true
    entryPoint: http

entryPoints:
  http:
    address: ':80'
    http:
      redirections:
        entryPoint:
          to: 'https'
          scheme: 'https'
          permanent: true
  https:
    address: ':443'
    transport:
      respondingTimeouts:
        readTimeout: 600s
        idleTimeout: 600s
        writeTimeout: 600s
    http:
      tls:
        certResolver: 'cloudflare'

serversTransport:
  insecureSkipVerify: true

providers:
  docker:
    endpoint: 'unix:///var/run/docker.sock'
    exposedByDefault: false
    network: proxy
  file:
    filename: '/dynamic.yml'

certificatesResolvers:
  cloudflare:
    acme:
      email: '{{ env "CF_API_EMAIL" }}'
      storage: '/data/acme.json'
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"

tls:
  options:
    default:
      minVersion: 'VersionTLS12'
      cipherSuites:
        - 'TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256'
        - 'TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256'
        - 'TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384'
        - 'TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384'
        - 'TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305'
        - 'TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305'
